---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
    driver_config:
      network:
      - ["forwarded_port", {guest: 3000, host: 3000}]

suites:
  - name: default
    run_list:
      - recipe[strider-cd::default]
    attributes: